sudo: required
dist: xenial

language: node_js

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ppa:ansible/ansible
    packages:
    - gcc-6
    - g++-6
    - software-properties-common
    - ansible

services:
 - mysql

env:
- TEST_TYPE="unit_tests"
- TEST_TYPE="functional_tests"
- TEST_TYPE="component_tests"

before_script:
 - bash tests/install.sh
 - bash tests/compile.sh

script:
 - bash tests/test_runner.sh

after_script:
 - ./main_server/node_modules/.bin/codecov -F ${TEST_TYPE:0:-6}
